- name: Install Core Packages For Neovim (lua)
  become: yes
  pacman:
    name: ["lua"]
  tags:
    - nvim
    - core
    - install
- name: Install C Enviroment
  become: yes
  pacman:
    name: ["make", "pkg-config", "clang", "bear"]
  tags:
    - dotfiles
    - core
    - install
- name: Install Core Packages (system utils)
  become: yes
  pacman:
    name: ["unzip", "fzf", "ripgrep", "htop", "curl", "man", "which"]
  tags:
    - core
    - install
- name: Install Desktop Enviroment Packages I
  become: yes
  pacman:
    name: ["yad", "wl-clipboard", "ttf-nerd-fonts-symbols", "swaylock", "ttf-firacode", "grim", "mako", "swaybg", "wofi", "feh", "sddm", "hyprland", "pavucontrol", "firefox", "qbittorrent", "nautilus", "alacritty", "mpv", "pipewire", "wireplumber", "pipewire-pulse"]
  tags:
    - install
    - desktop
- name: Allow the user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "{{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
- name: Install Desktop Enviroment Packages II (AUR)
  kewlfft.aur.aur:
    name: waybar-git xfce-toolkit wlogout
    use: makepkg
    state: present
  tags:
    - install
    - desktop
- name: Enable Display Manager
  become: yes
  ansible.builtin.systemd:
    name: sddm
    enabled: true
  tags:
    - install
    - desktop
    - systemd
