- name: Install Pass
  become: yes
  pacman: name=pass
  tags:
    - install
    - password-store
- name: Clone git repo w/ passwords
  git:
    repo: git@gitlab.com:guilaft/passwords.git
    dest: "{{ lookup('env', 'HOME') }}/.password-store"
    accept_hostkey: yes
    version: main
  tags:
    - password-store
