- name: Install Tmux
  become: yes
  pacman: name=tmux
  tags:
    - install
    - tmux
- name: Create a Tmux plugins directory if it does not exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.tmux/plugins"
    state: directory
    mode: '0755'
- name: Install TPM
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - tmux
- name: Run TPM install plugins script
  shell: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm/scripts/install_plugins.sh"
